version: '3.9'
services:
    app:
        volumes:
            - .:/app
            - /app/node_modules
        command: >
            sh -c "npx prisma migrate deploy &&
                   npm run prisma:seed:category &&
                   npm run start:dev"
