export enum NotificationType {
    NEW_MESSAGE = 'NEW_MESSAGE',
    NEW_ORDER = 'NEW_ORDER',
    NEW_REVIEW = 'NEW_REVIEW',
    NEW_INVOICE = 'NEW_INVOICE',
    NEW_OFFER = 'NEW_OFFER',
    BID_STATUS_CHANGED = 'BID_STATUS_CHANGED',
    INVOICE_STATUS_CHANGED = 'INVOICE_STATUS_CHANGED',
    ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
    GROUP_PURCHASE_STATUS_CHANGED = 'GROUP_PURCHASE_STATUS_CHANGED',
}
