import { tap } from 'rxjs';
import {
    BadRequestException,
    Injectable,
    InternalServerErrorException,
} from '@nestjs/common';
import axios from 'axios';

@Injectable()
export class TapPaymentsService {
    /**
     * Creates a new customer in Tap Payments.
     *
     * Sends a POST request to the Tap Payments API with the provided customer information.
     *
     * @param {Object} data - Customer information.
     * @param {string} data.first_name - Customer's first name.
     * @param {string} [data.middle_name] - Customer's middle name (optional).
     * @param {string} [data.last_name] - Customer's last name (optional).
     * @param {string} data.email - Customer's email address.
     * @param {Object} [data.phone] - Customer's phone information (optional).
     * @param {string} data.phone.country_code - Country code of the phone number (e.g., '966').
     * @param {string} data.phone.number - Phone number without country code.
     *
     * @returns {Promise<string>} The ID of the newly created Tap customer.
     *
     * @throws {Error} Throws an error if the API request fails. The error message will contain
     * the response from Tap Payments if available, or the generic error message.
     *
     * @example
     * const customerId = await tapService.createCustomer({
     *   first_name: 'John',
     *   last_name: 'Doe',
     *   email: 'john.doe@example.com',
     *   phone: { country_code: '966', number: '500000000' },
     * });
     * console.log(customerId); // e.g., 'cus_123456789'
     */
    async createCustomer(data: {
        first_name: string;
        middle_name?: string;
        last_name?: string;
        email: string;
        phone?: { country_code: string; number: string };
    }) {
        try {
            const response = await axios.post(
                'https://api.tap.company/v2/customers/',
                data,
                {
                    headers: {
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                        'Content-Type': 'application/json',
                    },
                },
            );
            return response.data.id;
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw err;
        }
    }

    /**
     * Creates a charge in Tap Payments using a card token.
     *
     * This method is required to save a card in Tap. It performs a minimal charge (default 1 SAR)
     * and marks `save_card: true` so the card is stored for future use.
     * The `redirect.url` is required by Tap but can be a placeholder if you don't want the user to be redirected.
     *
     * @param {string} tokenId - The card token generated by Tap SDK (token.card.id).
     * @param {Object} customerData - Customer information.
     * @param {string} customerData.first_name - Customer's first name.
     * @param {string} customerData.email - Customer's email address.
     * @param {number} [amount=1] - Amount to charge (default is 1).
     * @param {string} [currency='SAR'] - Currency code (default is 'SAR').
     *
     * @returns {Promise<Object>} The charge object returned by Tap.
     *
     * @throws {Error} Throws an error if the charge creation fails.
     *
     * @example
     * const charge = await tapService.createCharge('card_TS65A38251713Ny0d192G8O876', {
     *   first_name: 'Shahad',
     *   email: 'shahad@example.com'
     * });
     */
    async createCharge(
        tokenId: string,
        tapCustomerId: string,
        redirectUrl: string,
        amount: number = 1,
        currency: string = 'SAR',
    ) {
        try {
            const response = await axios.post(
                'https://api.tap.company/v2/charges/',
                {
                    amount,
                    currency,
                    customer_initiated: true,
                    threeDSecure: true,
                    save_card: true, // mark true to save the card
                    description: 'Card save charge',
                    metadata: { udf1: 'Save card test' },
                    receipt: { email: false, sms: false },
                    // reference: {
                    //     transaction: `txn_${Date.now()}`,
                    //     order: `ord_${Date.now()}`,
                    // },
                    customer: { id: tapCustomerId },
                    merchant: { id: process.env.TAP_MERCHANT_ID },
                    source: { id: tokenId },
                    // post: { url: 'http://your_website.com/post_url' },
                    redirect: { url: redirectUrl }, // redirect URL required by Tap to redirect after 3DS (OTP step)
                },
                {
                    headers: {
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                    },
                },
            );
            return response.data;
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw new Error('Failed to create charge in Tap');
        }
    }

    /**
     * Retrieves a charge from Tap Payments by chargeId.
     *
     * @param {string} chargeId - The Tap charge ID (chg_xxx).
     * @returns {Promise<any>} The charge object from Tap.
     *
     * @throws {Error} Throws an error if the request fails.
     *
     * @example
     * const charge = await tapService.getCharge('chg_TS50A42252049msSJ23MV8k170');
     * console.log(charge.status); // "CAPTURED" | "AUTHORIZED" | "FAILED"
     */
    async getCharge(chargeId: string) {
        try {
            const response = await axios.get(
                `https://api.tap.company/v2/charges/${chargeId}`,
                {
                    headers: {
                        accept: 'application/json',
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                    },
                },
            );
            return response.data;
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw new Error(`Failed to fetch charge ${chargeId} from Tap`);
        }
    }

    /**
     * Retrieves a card from Tap using customerId and cardId.
     * @param customerId Tap customer ID (cus_xxx)
     * @param cardId Tap card ID (card_xxx)
     * @returns The card object from Tap
     */
    async getCard(customerId: string, cardId: string) {
        try {
            const response = await axios.get(
                `https://api.tap.company/v2/card/${customerId}/${cardId}`,
                {
                    headers: {
                        accept: 'application/json',
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                    },
                },
            );
            return response.data;
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw new Error('Failed to fetch card from Tap');
        }
    }

    /**
     * Deletes a saved card in Tap Payments for a given customer.
     *
     * @param {string} customerId - The Tap customer ID (cus_xxx).
     * @param {string} cardId - The Tap card ID (card_xxx).
     * @returns {Promise<void>} Resolves if deletion succeeds, throws otherwise.
     */
    async deleteCard(customerId: string, cardId: string): Promise<void> {
        try {
            await axios.delete(
                `https://api.tap.company/v2/card/${customerId}/${cardId}`,
                {
                    headers: {
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                        Accept: 'application/json',
                    },
                },
            );
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw new Error('Failed to delete card from Tap');
        }
    }

    /**
     * Creates a payment token from a saved card in Tap Payments.
     *
     * @param {string} tapCustomerId - Tap customer ID (cus_xxx)
     * @param {string} tapCardId - Tap saved card ID (card_xxx)
     * @param {string} [clientIp='127.0.0.1'] - Client IP address (for fraud checks)
     *
     * @returns {Promise<Object>} Tap token object
     */
    async createTokenFromSavedCard(
        tapCustomerId: string,
        tapCardId: string,
        clientIp: string = '127.0.0.1',
    ) {
        try {
            const response = await axios.post(
                'https://api.tap.company/v2/tokens/',
                {
                    saved_card: {
                        card_id: tapCardId,
                        customer_id: tapCustomerId,
                    },
                    client_ip: clientIp,
                },
                {
                    headers: {
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                    },
                },
            );

            return response.data;
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw new Error('Failed to create token from saved card');
        }
    }

    /**
     * Charges a saved card in Tap Payments.
     *
     * @param {string} tapCustomerId - Tap customer ID (cus_xxx)
     * @param {string} tapCardId - Tap saved card ID (card_xxx)
     * @param {number} amount - Amount in minor units (e.g., 100 = 1.00 SAR)
     * @param {string} [currency='SAR'] - Currency code
     * @param {string} redirectUrl - Redirect URL after 3DS authentication
     *
     * @returns {Promise<Object>} Tap charge object
     */
    async payWithSavedCard(
        tapCustomerId: string,
        tokenId: string, // int here? tbh better
        tapCardId: string,
        amount: number,
        redirectUrl: string,
        currency: string = 'SAR',
    ) {
        try {
            const response = await axios.post(
                'https://api.tap.company/v2/charges/',
                {
                    amount, // must already be in minor units
                    currency,
                    customer_initiated: true,
                    threeDSecure: true,
                    description: 'Cart payment',
                    customer: { id: tapCustomerId },
                    source: {
                        id: tokenId,
                    },
                    redirect: { url: redirectUrl }, // REQUIRED for 3DS
                },
                {
                    headers: {
                        Authorization: `Bearer ${process.env.TAP_SECRET_KEY}`,
                        'Content-Type': 'application/json',
                        Accept: 'application/json',
                    },
                },
            );

            return response.data;
        } catch (err: any) {
            console.error(err.response?.data || err.message);
            throw new Error('Failed to charge saved card');
        }
    }

    async validateCharge(charge: any) {
        const createdMs =
            charge.transaction?.created || charge.transaction?.date?.created;
        if (!createdMs) {
            throw new InternalServerErrorException(
                'Cannot determine charge creation time.',
            );
        }

        const chargeCreationTime = new Date(Number(createdMs));
        const now = new Date();

        const timeDifference = now.getTime() - chargeCreationTime.getTime();

        // 1 hour = 3600000 ms
        if (timeDifference > 3600000) {
            throw new BadRequestException(
                'Charge ID is too old. Please initiate a new payment.',
            );
        }
    }
}
