import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import {
  ApiHideProperty,
  ApiOkResponse,
  ApiOperation,
  ApiTags,
} from '@nestjs/swagger';

@ApiTags('Default')
@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @ApiHideProperty()
  @Get()
  @ApiOperation({
    deprecated: true,
    summary: 'Not a usable endpoint',
    description:
      'This is the default root endpoint generated by NestJS. It returns a static test message and is not part of the real Silah API.',
  })
  @ApiOkResponse({
    description: 'A "Hello, World!" message.',
    schema: {
      type: 'string',
      example: 'Hello, World!',
    },
  })
  getHello(): string {
    return this.appService.getHello();
  }
}
