name: Update Swagger Docs

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Silah Backend
              uses: actions/checkout@v3
              with:
                  path: backend

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install backend dependencies
              run: npm ci
              working-directory: ./backend

            - name: Build backend
              run: npm run build
              working-directory: ./backend

            - name: Generate swagger.json
              run: node dist/scripts/generate-swagger.js
              working-directory: ./backend

            - name: Checkout Silah API Docs repo
              uses: actions/checkout@v3
              with:
                  repository: GP-Silah/silah-api-docs
                  token: ${{ secrets.GITHUB_TOKEN }}
                  path: docs-repo

            - name: Copy swagger.json to docs repo
              run: cp ./backend/docs/swagger.json ./docs-repo/docs/swagger.json

            - name: Commit and push changes
              run: |
                  cd docs-repo
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add docs/swagger.json
                  git commit -m "Update swagger.json"
                  git push origin main
